package com.practica.apidrogueria.models.entity;

public enum Tipo {

    ANTIBIOTICO, ANTIINFLAMATORIO, ANTIHISTAMINICO, EXPECTORANTE, ANTIALERGICO, ANTIESPASMODICO, ANTISEPTICO,

    ANTIDEPRESIVO, LAXANTE, VITAMINA, SUPLEMENTO, ANTIGRIPAL, CREMA, CREMAVAGINAL, OVULO, OTRO;

}
